version: 2

models:
    - name: batting
      description: "Table stores the batting records of Zen cricket players"
      columns:
          - name: season_nm
            description: "Name of tournament season"
          - name: season_rank
            description: "Tournament season rank of the player"
          - name: player_nm
            description: "Name of the player"
          - name: group_nm
            description: "Group Name of the tournament season"
          - name: team_nm
            description: "Name of the team"
          - name: bat_match_cnt
            description: "Total Matches played"
          - name: bat_innings_cnt
            description: "Total innings played from batting side"
          - name:  notout_cnt
            description: "Total innings count the player did not get out"
          - name: run_cnt
            description: "Total runs scored by the player"
          - name: four_cnt
            description: "Total boundaries scored by the player"
          - name: six_cnt
            description: "Total sixes scored by the player"
          - name: fifty_cnt
            description: "Total fifties scored by the player"
          - name: hundred_cnt
            description: "Total hundreds scored by the player"
          - name: high_score
            description: "Highest score scored by the player"
          - name: bat_strike_rate
            description: "Batting strike rate of the player for given tournament season"
          - name: batting_avg
            description: "Batting average of the player for given tournament season"
          - name: bat_attack_rate
            description: "Attack rate measure is defined as bat_strike_rate * batting_avg to measure how fast a player scores more runs in a tournament"
          - name: "bat_opportunity_rate"
            description: "Defines the batting opportunity of the player"
          - name: created_utc
            description: "Created UTC timestamp of the record"
          - name: created_by
            description: "Created user of the record"
          - name: updated_utc
            description: "Updated UTC timestamp of the record"
          - name: updated_by
            description: "Updated user of the record"
          - name: source_nm
            description: "Source name of the dataset"
    - name: bowling
      description: "Table stores the bowling records of Zen cricket players"
      columns:
        - name: season_nm
          description: "Name of tournament season"
        - name: season_rank
          description: "Tournament season rank of the player"
        - name: player_nm
          description: "Name of the player"
        - name: group_nm
          description: "Group Name of the tournament season"
        - name: team_nm
          description: "Name of the team"
        - name: bowl_match_cnt
          description: "Total Matches played"
        - name: bowl_innings_cnt
          description: "Total innings played from bowling side"
        - name:  overs_cnt
          description: "Total overs bowled by the player. It is numeric column to account the unfinished overs as well"
        - name: conceded_runs_cnt
          description: "Total runs conceded by the bowler"
        - name: wicket_cnt
          description: "Total wickets taken"
        - name: maiden_cnt
          description: "Total maidens overs bowled"
        - name: dot_ball_cnt
          description: "Total dot balls bowled"
        - name: economy_rate
          description: "Economy rate of the bowler calculated by runs conceded against bowled overs"
        - name: bowling_avg
          description: "Bowling average of the player for given tournament season"
        - name: bowl_strike_rate
          description: "Bowling strike rate of the player for given tournament season"
        - name: hat_trick_cnt
          description: "Hat trick wickets taken for given tournament season"
        - name: four_wkt_haul_cnt
          description: "Count of innings where bowler taken 4 wickets"
        - name: five_wkt_haul_cnt
          description: "Count of innings where bowler taken greater than or equal 5 wickets"
        - name: "wide_cnt"
          description: "Total wides given"
        - name: "no_ball_cnt"
          description: "Total no balls bowled"
        - name: "ball_cnt"
          description: "Total balls bowled"
        - name: "min_overs_bowled_cnt"
          description: "Minimum number of overs bowled per innings"
        - name: bowl_attack_rate
          description: "Bowl Attack rate measure is defined as (1/bowl_strike_rate) * wicket_cnt to measure how fast a player takes more wickets in a tournament"
        - name: "best_bowling_figure"
          description: "Best bowling figure of the tournament"
        - name: "bowl_opportunity_rate"
          description: "Defines the bowling opportunity of the player"
        - name: created_utc
          description: "Created UTC timestamp of the record"
        - name: created_by
          description: "Created user of the record"
        - name: updated_utc
          description: "Updated UTC timestamp of the record"
        - name: updated_by
          description: "Updated user of the record"
        - name: source_nm
          description: "Source name of the dataset"
    - name: "players"
      description: "Table stores the player details of Zen cricket players"
      columns:
        - name : player_id
          description : "Id of the player"
        - name: player_nm
          description: "Name of the player"
        - name: season_nm
          description: "Name of tournament season"
        - name: division_nm
          description: "Name of the division"
        - name: team_nm
          description: "Name of the team"
        - name: season_nm_lst
          description: "List of seasons played"
        - name: division_nm_lst
          description: "List of divisions played"
        - name: team_nm_lst
          description: "List of teams played"
        - name: team_cnt
          description: "Count of teams played"
        - name: season_cnt
          description: "Count of seasons played"
        - name: created_utc
          description: "Created UTC timestamp of the record"
        - name: created_by
          description: "Created user of the record"
        - name: updated_utc
          description: "Updated UTC timestamp of the record"
        - name: updated_by
          description: "Updated user of the record"
        - name: source_nm
          description: "Source name of the dataset"

          


          

